# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(883, 571)
        self.judul = QtWidgets.QLabel(Form)
        self.judul.setGeometry(QtCore.QRect(110, 10, 631, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.judul.setFont(font)
        self.judul.setObjectName("judul")
        self.csv_button = QtWidgets.QRadioButton(Form)
        self.csv_button.setGeometry(QtCore.QRect(450, 160, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.csv_button.setFont(font)
        self.csv_button.setObjectName("csv_button")
        self.csv_edit = QtWidgets.QLineEdit(Form)
        self.csv_edit.setGeometry(QtCore.QRect(570, 160, 191, 20))
        self.csv_edit.setObjectName("csv_edit")
        self.csv_browse = QtWidgets.QPushButton(Form)
        self.csv_browse.setGeometry(QtCore.QRect(770, 160, 75, 23))
        self.csv_browse.setObjectName("csv_browse")
        self.pos_edit = QtWidgets.QLineEdit(Form)
        self.pos_edit.setGeometry(QtCore.QRect(160, 160, 171, 20))
        self.pos_edit.setObjectName("pos_edit")
        self.pos_browse = QtWidgets.QPushButton(Form)
        self.pos_browse.setGeometry(QtCore.QRect(340, 160, 75, 23))
        self.pos_browse.setObjectName("pos_browse")
        self.str_button = QtWidgets.QRadioButton(Form)
        self.str_button.setGeometry(QtCore.QRect(450, 200, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.str_button.setFont(font)
        self.str_button.setObjectName("str_button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(470, 290, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.metode_combo = QtWidgets.QComboBox(Form)
        self.metode_combo.setGeometry(QtCore.QRect(470, 310, 111, 22))
        self.metode_combo.setObjectName("metode_combo")
        self.metode_combo.addItem("")
        self.metode_combo.addItem("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(620, 290, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.k_combo = QtWidgets.QComboBox(Form)
        self.k_combo.setGeometry(QtCore.QRect(620, 310, 51, 22))
        self.k_combo.setObjectName("k_combo")
        self.k_combo.addItem("")
        self.k_combo.addItem("")
        self.k_combo.addItem("")
        self.k_combo.addItem("")
        self.k_combo.addItem("")
        self.k_combo.addItem("")
        self.k_combo.addItem("")
        self.k_combo.addItem("")
        self.k_combo.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 280, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.str_edit = QtWidgets.QPlainTextEdit(Form)
        self.str_edit.setGeometry(QtCore.QRect(570, 200, 191, 71))
        self.str_edit.setObjectName("str_edit")
        self.kelas = QtWidgets.QLabel(Form)
        self.kelas.setGeometry(QtCore.QRect(540, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.kelas.setFont(font)
        self.kelas.setObjectName("kelas")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(180, 370, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.akurasi = QtWidgets.QLabel(Form)
        self.akurasi.setGeometry(QtCore.QRect(200, 390, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.akurasi.setFont(font)
        self.akurasi.setObjectName("akurasi")
        self.neg_edit = QtWidgets.QLineEdit(Form)
        self.neg_edit.setGeometry(QtCore.QRect(160, 200, 171, 20))
        self.neg_edit.setObjectName("neg_edit")
        self.neg_browse = QtWidgets.QPushButton(Form)
        self.neg_browse.setGeometry(QtCore.QRect(340, 200, 75, 23))
        self.neg_browse.setObjectName("neg_browse")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 240, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.train_edit = QtWidgets.QLineEdit(Form)
        self.train_edit.setGeometry(QtCore.QRect(160, 240, 171, 20))
        self.train_edit.setObjectName("train_edit")
        self.train_browse = QtWidgets.QPushButton(Form)
        self.train_browse.setGeometry(QtCore.QRect(340, 240, 75, 23))
        self.train_browse.setObjectName("train_browse")
        self.judul_2 = QtWidgets.QLabel(Form)
        self.judul_2.setGeometry(QtCore.QRect(40, 110, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.judul_2.setFont(font)
        self.judul_2.setObjectName("judul_2")
        self.submitButton = QtWidgets.QPushButton(Form)
        self.submitButton.setGeometry(QtCore.QRect(700, 280, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.positif = QtWidgets.QLabel(Form)
        self.positif.setGeometry(QtCore.QRect(210, 480, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.positif.setFont(font)
        self.positif.setObjectName("positif")
        self.negatif = QtWidgets.QLabel(Form)
        self.negatif.setGeometry(QtCore.QRect(520, 480, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.negatif.setFont(font)
        self.negatif.setObjectName("negatif")
        self.netral = QtWidgets.QLabel(Form)
        self.netral.setGeometry(QtCore.QRect(370, 480, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.netral.setFont(font)
        self.netral.setObjectName("netral")
        self.judul_3 = QtWidgets.QLabel(Form)
        self.judul_3.setGeometry(QtCore.QRect(460, 110, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.judul_3.setFont(font)
        self.judul_3.setObjectName("judul_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.judul.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Analisis Sentimen Bahasa Indonesia</span></p><p align=\"center\"><span style=\" font-size:20pt;\">Bagi Orang Asing</span></p></body></html>"))
        self.csv_button.setText(_translate("Form", "Select file (.txt)"))
        self.csv_browse.setText(_translate("Form", "Browse"))
        self.pos_browse.setText(_translate("Form", "Browse"))
        self.str_button.setText(_translate("Form", "Input sentence"))
        self.label.setText(_translate("Form", "Method:"))
        self.metode_combo.setItemText(0, _translate("Form", "Naive Bayes"))
        self.metode_combo.setItemText(1, _translate("Form", "k-NN"))
        self.label_2.setText(_translate("Form", "k:"))
        self.k_combo.setItemText(0, _translate("Form", "1"))
        self.k_combo.setItemText(1, _translate("Form", "2"))
        self.k_combo.setItemText(2, _translate("Form", "3"))
        self.k_combo.setItemText(3, _translate("Form", "4"))
        self.k_combo.setItemText(4, _translate("Form", "5"))
        self.k_combo.setItemText(5, _translate("Form", "6"))
        self.k_combo.setItemText(6, _translate("Form", "7"))
        self.k_combo.setItemText(7, _translate("Form", "8"))
        self.k_combo.setItemText(8, _translate("Form", "9"))
        self.pushButton.setText(_translate("Form", "START TRAINING"))
        self.kelas.setText(_translate("Form", "Kelas: ________"))
        self.label_4.setText(_translate("Form", "Accuracy:"))
        self.akurasi.setText(_translate("Form", "___%"))
        self.neg_browse.setText(_translate("Form", "Browse"))
        self.label_3.setText(_translate("Form", "Positive Sentiment"))
        self.label_5.setText(_translate("Form", "Negative Sentiment"))
        self.label_6.setText(_translate("Form", "Training"))
        self.train_browse.setText(_translate("Form", "Browse"))
        self.judul_2.setText(_translate("Form", "Modeling"))
        self.submitButton.setText(_translate("Form", "START TESTING"))
        self.positif.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">__%</span></p><p align=\"center\"><span style=\" font-size:16pt;\">POSITIF</span></p></body></html>"))
        self.negatif.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">__%</span></p><p align=\"center\"><span style=\" font-size:16pt;\">NEGATIF</span></p></body></html>"))
        self.netral.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">__%</span></p><p align=\"center\"><span style=\" font-size:16pt;\">NETRAL</span></p></body></html>"))
        self.judul_3.setText(_translate("Form", "Classification"))

